import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[window]
startup_mode = "Maximized"

[shell]
program = "tmux"
args = ["new-session", "-A", "-D", "-s main"]

[keyboard]
bindings = [{key = "NumpadEnter", chars = "\r"}]

[font]
normal = {family = "ShureTechMono Nerd Font"}

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
LC_CTYPE = "en_US.UTF-8"
