set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g status-left-length 100
set -g status-left "[#S] "
set -g status-right "#{user} - %d %b %Y - %H:%M"
set -g status-style bg=default,fg=white

set-option -g detach-on-destroy off
set -g focus-events on
set-option -g allow-passthrough on

set -g set-titles on
set -g set-titles-string "#{?#{==:#{pane_current_command},ssh},#{pane_title},#{window_name}@#{session_name}}"

set -g prefix M-a
unbind C-b
bind-key M-a send-prefix

unbind %
bind | split-window -h -c '#{pane_current_path}'

unbind '"'
bind - split-window -v -c '#{pane_current_path}'

bind c new-window -c '#{pane_current_path}'

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

set -sg escape-time 10

set -g renumber-windows on
